//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.22 at 08:04:20 AM SAST 
//


package haj.com.saqa.qualifications;

import javax.xml.bind.annotation.XmlRegistry;


// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the haj.com.saqa.qualifications package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: haj.com.saqa.qualifications
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SAQAQUALIFICATIONS.USQUALIFICATIONLINK }
     *
     * @return the usqualificationlink
     */
    public USQUALIFICATIONLINK createSAQAQUALIFICATIONSUSQUALIFICATIONLINK() {
        return new USQUALIFICATIONLINK();
    }

    /**
     * Create an instance of {@link SAQAQUALIFICATIONS.LPQUALIFICATIONLINK }
     *
     * @return the lpqualificationlink
     */
    public SAQAQUALIFICATIONS.LPQUALIFICATIONLINK createSAQAQUALIFICATIONSLPQUALIFICATIONLINK() {
        return new SAQAQUALIFICATIONS.LPQUALIFICATIONLINK();
    }

    /**
     * Create an instance of {@link SAQAQUALIFICATIONS.QUALIFICATION }
     *
     * @return the qualification
     */
    public QUALIFICATION createSAQAQUALIFICATIONSQUALIFICATION() {
        return new QUALIFICATION();
    }

    /**
     * Create an instance of {@link SAQAQUALIFICATIONS }.
     *
     * @return the saqaqualifications
     */
    public SAQAQUALIFICATIONS createSAQAQUALIFICATIONS() {
        return new SAQAQUALIFICATIONS();
    }

}
