using Nsdms.Domain.Entities;

namespace Nsdms.Application.Services;

/// <summary>
/// Finding generated by ISO 9001:2015 Clause 7.5 or DPSA Information Security Directive compliance checks.
/// </summary>
public record AuditComplianceFinding(
    string RuleId,
    string Standard,
    string Severity,
    string Description,
    bool IsPassed,
    string? Details = null);

/// <summary>
/// Comprehensive compliance evaluation report for ISO 9001 & DPSA Directive audit logging standards.
/// </summary>
public record AuditComplianceReport(
    DateTime GeneratedAtUtc,
    string AssessmentStatus,
    double ComplianceScorePercentage,
    int TotalAuditLogsExamined,
    int TotalEntitiesExamined,
    int VerifiedAtomicCommitCount,
    int PartialCommitViolationCount,
    List<AuditComplianceFinding> Findings,
    string DigitalSecuritySeal);

/// <summary>
/// Service providing statutory and quality governance evaluations across the audit trail.
/// Verifies zero partial commits, ISO 9001 Clause 7.5 documented information traceability,
/// and DPSA Directive public sector ICT audit compliance.
/// </summary>
public interface IIsoDpsaAuditComplianceService
{
    /// <summary>
    /// Executes a complete statutory audit verification across all compliance dimensions,
    /// calculating an overall compliance score and returning a tamper-evident audit report.
    /// </summary>
    Task<AuditComplianceReport> RunFullComplianceAuditAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies zero partial commits: asserts that sampled entities in domain tables have corresponding
    /// persistent AuditLog entries with non-zero IDs, and no orphan audit logs exist.
    /// </summary>
    Task<List<AuditComplianceFinding>> VerifyZeroPartialCommitsAsync(int sampleLimit = 500, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies ISO 9001:2015 Clause 7.5 (Control of Documented Information) compliance:
    /// persistent unique identification, before/after state snapshots, and tamper protection.
    /// </summary>
    Task<List<AuditComplianceFinding>> VerifyIso9001ComplianceAsync(int sampleSize = 1000, CancellationToken cancellationToken = default);

    /// <summary>
    /// Verifies DPSA Directive on Corporate Governance of ICT & Public Service Information Security compliance:
    /// zero anonymous actors, UTC timestamp precision, POPIA sensitive PII masking, and Maker-Checker segregation of duties.
    /// </summary>
    Task<List<AuditComplianceFinding>> VerifyDpsaDirectiveComplianceAsync(int sampleSize = 1000, CancellationToken cancellationToken = default);

    /// <summary>
    /// Computes the cryptographic SHA-256 seal for an individual audit log entry.
    /// </summary>
    string ComputeAuditRecordSecuritySeal(AuditLog log);

    /// <summary>
    /// Verifies whether the digital security seal in an audit entry's metadata matches its content.
    /// </summary>
    bool VerifyAuditRecordSecuritySeal(AuditLog log);
}
