package haj.com.entity.lookup;
// Generated Oct 23, 2017 5:04:50 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * SaqaQualification generated by hbm2java.
 */
@Entity
@Table(name = "saqa_qualification"

)
public class SaqaQualification implements IDataEntity {

	/** The id. */
	private Long id;

	/** The abetbanddescription. */
	private String abetbanddescription;

	/** The eloacqualassessmentcriteria. */
	private String eloacqualassessmentcriteria;

	/** The eloacqualificationoutcome. */
	private String eloacqualificationoutcome;

	/** The etqaid. */
	protected String etqaid;

	/** The etqaacronym. */
	private String etqaacronym;

	/** The etqaname. */
	private String etqaname;

	/** The field. */
	private String field;

	/** The fielddescription. */
	private String fielddescription;

	/** The islearningprogramme. */
	private String islearningprogramme;

	/** The learningprogrammequal. */
	private Integer learningprogrammequal;

	/** The nqfleveldescription. */
	private String nqfleveldescription;

	/** The nqflevelg 2 description. */
	private String nqflevelg2description;

	/** The providercode. */
	private String providercode;

	/** The provideretqaid. */
	private Integer provideretqaid;

	/** The providername. */
	private String providername;

	/** The qualarticulationoptions. */
	private String qualarticulationoptions;

	/** The qualassessorcriteria. */
	private String qualassessorcriteria;

	/** The qualificationclassdesc. */
	private String qualificationclassdesc;

	/** The qualificationid. */
	private Integer qualificationid;

	/** The qualificationid. */
	private String qualificationidString;

	/** The qualificationminimumcredits. */
	private Integer qualificationminimumcredits;

	/** The qualificationnotes. */
	private String qualificationnotes;

	/** The qualificationpurpose. */
	private String qualificationpurpose;

	/** The qualificationtitle. */
	private String qualificationtitle;

	/** The qualificationtypeid. */
	private String qualificationtypeid;

	/** The qualificationtypedesc. */
	private String qualificationtypedesc;

	/** The qualintlbenchmarkingmemo. */
	private String qualintlbenchmarkingmemo;

	/** The quallearningassumedinplace. */
	private String quallearningassumedinplace;

	/** The qualmoderationoptions. */
	private String qualmoderationoptions;

	/** The qualrulesofcombination. */
	private String qualrulesofcombination;

	/** The recognizeprevlearningflag. */
	private String recognizeprevlearningflag;

	/** The registrationstatusdesc. */
	private String registrationstatusdesc;

	/** The registrationstatuscode. */
	private String registrationstatuscode;

	/** The saqadecisionnumber. */
	private String saqadecisionnumber;

	/** The sgbname. */
	private String sgbname;

	/** The subfielddescription. */
	private String subfielddescription;

	/** The trainoutperiod. */
	private Integer trainoutperiod;

	/** The transitionperiod. */
	private Integer transitionperiod;

	/** The saqa us qualifications. */
	private Set<SaqaUsQualification> saqaUsQualifications = new HashSet<SaqaUsQualification>(0);

	/** The nqflevel id. */
	private String nqflevelId;

	/** The nqflevel. */
	private NqfLevels nqflevel;

	/** indicator if qualification requires work place approval */
	private Boolean workplaceApprovalRequired;

	/** The last date for enrolment */
	@Column(name = "last_date_for_enrolment", nullable = true)
	private Date lastDateForEnrolment;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastdateforachievement", nullable = true)
	private Date lastdateforachievement;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "qualregistrationstartdate", nullable = true)
	private Date qualregistrationstartDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "qualregistrationenddate", nullable = true)
	private Date qualregistrationendDate;

	private DesignatedTrade designatedTrade;

	private LearnerMentorRatio learnerMentorRatio;

	/** The trainoutperiod. */
	private Integer levelOne;

	/** The transitionperiod. */
	private Integer levelTwo;

	/** The trainoutperiod. */
	private Integer levelThree;

	/** The transitionperiod. */
	private Integer levelFour;

	/**
	 * Instantiates a new saqa qualification.
	 */
	public SaqaQualification() {
	}

	/**
	 * Instantiates a new saqa qualification.
	 *
	 * @param abetbanddescription
	 *            the abetbanddescription
	 * @param eloacqualassessmentcriteria
	 *            the eloacqualassessmentcriteria
	 * @param eloacqualificationoutcome
	 *            the eloacqualificationoutcome
	 * @param etqaacronym
	 *            the etqaacronym
	 * @param etqaname
	 *            the etqaname
	 * @param field
	 *            the field
	 * @param fielddescription
	 *            the fielddescription
	 * @param islearningprogramme
	 *            the islearningprogramme
	 * @param learningprogrammequal
	 *            the learningprogrammequal
	 * @param nqfleveldescription
	 *            the nqfleveldescription
	 * @param nqflevelg2description
	 *            the nqflevelg 2 description
	 * @param providercode
	 *            the providercode
	 * @param provideretqaid
	 *            the provideretqaid
	 * @param providername
	 *            the providername
	 * @param qualarticulationoptions
	 *            the qualarticulationoptions
	 * @param qualassessorcriteria
	 *            the qualassessorcriteria
	 * @param qualificationclassdesc
	 *            the qualificationclassdesc
	 * @param qualificationid
	 *            the qualificationid
	 * @param qualificationminimumcredits
	 *            the qualificationminimumcredits
	 * @param qualificationnotes
	 *            the qualificationnotes
	 * @param qualificationpurpose
	 *            the qualificationpurpose
	 * @param qualificationtitle
	 *            the qualificationtitle
	 * @param qualificationtypedesc
	 *            the qualificationtypedesc
	 * @param qualificationtypeid
	 *            the qualificationtypeid
	 * @param qualintlbenchmarkingmemo
	 *            the qualintlbenchmarkingmemo
	 * @param quallearningassumedinplace
	 *            the quallearningassumedinplace
	 * @param qualmoderationoptions
	 *            the qualmoderationoptions
	 * @param qualrulesofcombination
	 *            the qualrulesofcombination
	 * @param recognizeprevlearningflag
	 *            the recognizeprevlearningflag
	 * @param registrationstatusdesc
	 *            the registrationstatusdesc
	 * @param registrationstatuscode
	 *            the registrationstatuscode
	 * @param saqadecisionnumber
	 *            the saqadecisionnumber
	 * @param sgbname
	 *            the sgbname
	 * @param subfielddescription
	 *            the subfielddescription
	 * @param trainoutperiod
	 *            the trainoutperiod
	 * @param transitionperiod
	 *            the transitionperiod
	 * @param saqaUsQualifications
	 *            the saqa us qualifications
	 */
	public SaqaQualification(String abetbanddescription, String eloacqualassessmentcriteria, String eloacqualificationoutcome, String etqaacronym, String etqaname, String field, String fielddescription, String islearningprogramme, Integer learningprogrammequal, String nqfleveldescription, String nqflevelg2description, String providercode, Integer provideretqaid, String providername, String qualarticulationoptions, String qualassessorcriteria, String qualificationclassdesc,
			Integer qualificationid, Integer qualificationminimumcredits, String qualificationnotes, String qualificationpurpose, String qualificationtitle, String qualificationtypedesc, String qualificationtypeid, String qualintlbenchmarkingmemo, String quallearningassumedinplace, String qualmoderationoptions, String qualrulesofcombination, String recognizeprevlearningflag, String registrationstatusdesc, String registrationstatuscode, String saqadecisionnumber, String sgbname,
			String subfielddescription, Integer trainoutperiod, Integer transitionperiod, Set<SaqaUsQualification> saqaUsQualifications) {
		this.abetbanddescription = abetbanddescription;
		this.eloacqualassessmentcriteria = eloacqualassessmentcriteria;
		this.eloacqualificationoutcome = eloacqualificationoutcome;
		this.etqaacronym = etqaacronym;
		this.etqaname = etqaname;
		this.field = field;
		this.fielddescription = fielddescription;
		this.islearningprogramme = islearningprogramme;
		this.learningprogrammequal = learningprogrammequal;
		this.nqfleveldescription = nqfleveldescription;
		this.nqflevelg2description = nqflevelg2description;
		this.providercode = providercode;
		this.provideretqaid = provideretqaid;
		this.providername = providername;
		this.qualarticulationoptions = qualarticulationoptions;
		this.qualassessorcriteria = qualassessorcriteria;
		this.qualificationclassdesc = qualificationclassdesc;
		this.qualificationid = qualificationid;
		this.qualificationminimumcredits = qualificationminimumcredits;
		this.qualificationnotes = qualificationnotes;
		this.qualificationpurpose = qualificationpurpose;
		this.qualificationtitle = qualificationtitle;
		this.qualificationtypedesc = qualificationtypedesc;
		this.qualificationtypeid = qualificationtypeid;
		this.qualintlbenchmarkingmemo = qualintlbenchmarkingmemo;
		this.quallearningassumedinplace = quallearningassumedinplace;
		this.qualmoderationoptions = qualmoderationoptions;
		this.qualrulesofcombination = qualrulesofcombination;
		this.recognizeprevlearningflag = recognizeprevlearningflag;
		this.registrationstatusdesc = registrationstatusdesc;
		this.registrationstatuscode = registrationstatuscode;
		this.saqadecisionnumber = saqadecisionnumber;
		this.sgbname = sgbname;
		this.subfielddescription = subfielddescription;
		this.trainoutperiod = trainoutperiod;
		this.transitionperiod = transitionperiod;
		this.saqaUsQualifications = saqaUsQualifications;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id
	 *            the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the abetbanddescription.
	 *
	 * @return the abetbanddescription
	 */
	@Column(name = "abetbanddescription")
	public String getAbetbanddescription() {
		return this.abetbanddescription;
	}

	/**
	 * Sets the abetbanddescription.
	 *
	 * @param abetbanddescription
	 *            the new abetbanddescription
	 */
	public void setAbetbanddescription(String abetbanddescription) {
		this.abetbanddescription = abetbanddescription;
	}

	/**
	 * Gets the eloacqualassessmentcriteria.
	 *
	 * @return the eloacqualassessmentcriteria
	 */
	@Column(name = "eloacqualassessmentcriteria")
	public String getEloacqualassessmentcriteria() {
		return this.eloacqualassessmentcriteria;
	}

	/**
	 * Sets the eloacqualassessmentcriteria.
	 *
	 * @param eloacqualassessmentcriteria
	 *            the new eloacqualassessmentcriteria
	 */
	public void setEloacqualassessmentcriteria(String eloacqualassessmentcriteria) {
		this.eloacqualassessmentcriteria = eloacqualassessmentcriteria;
	}

	/**
	 * Gets the eloacqualificationoutcome.
	 *
	 * @return the eloacqualificationoutcome
	 */
	@Column(name = "eloacqualificationoutcome")
	public String getEloacqualificationoutcome() {
		return this.eloacqualificationoutcome;
	}

	/**
	 * Sets the eloacqualificationoutcome.
	 *
	 * @param eloacqualificationoutcome
	 *            the new eloacqualificationoutcome
	 */
	public void setEloacqualificationoutcome(String eloacqualificationoutcome) {
		this.eloacqualificationoutcome = eloacqualificationoutcome;
	}

	/**
	 * Gets the etqaacronym.
	 *
	 * @return the etqaacronym
	 */
	@Column(name = "etqaacronym")
	public String getEtqaacronym() {
		return this.etqaacronym;
	}

	/**
	 * Sets the etqaacronym.
	 *
	 * @param etqaacronym
	 *            the new etqaacronym
	 */
	public void setEtqaacronym(String etqaacronym) {
		this.etqaacronym = etqaacronym;
	}

	/**
	 * Gets the etqaname.
	 *
	 * @return the etqaname
	 */
	@Column(name = "etqaname")
	public String getEtqaname() {
		return this.etqaname;
	}

	/**
	 * Sets the etqaname.
	 *
	 * @param etqaname
	 *            the new etqaname
	 */
	public void setEtqaname(String etqaname) {
		this.etqaname = etqaname;
	}

	/**
	 * Gets the field.
	 *
	 * @return the field
	 */
	@Column(name = "field")
	public String getField() {
		return this.field;
	}

	/**
	 * Sets the field.
	 *
	 * @param field
	 *            the new field
	 */
	public void setField(String field) {
		this.field = field;
	}

	/**
	 * Gets the fielddescription.
	 *
	 * @return the fielddescription
	 */
	@Column(name = "fielddescription")
	public String getFielddescription() {
		return this.fielddescription;
	}

	/**
	 * Sets the fielddescription.
	 *
	 * @param fielddescription
	 *            the new fielddescription
	 */
	public void setFielddescription(String fielddescription) {
		this.fielddescription = fielddescription;
	}

	/**
	 * Gets the islearningprogramme.
	 *
	 * @return the islearningprogramme
	 */
	@Column(name = "islearningprogramme")
	public String getIslearningprogramme() {
		return this.islearningprogramme;
	}

	/**
	 * Sets the islearningprogramme.
	 *
	 * @param islearningprogramme
	 *            the new islearningprogramme
	 */
	public void setIslearningprogramme(String islearningprogramme) {
		this.islearningprogramme = islearningprogramme;
	}

	/**
	 * Gets the learningprogrammequal.
	 *
	 * @return the learningprogrammequal
	 */
	@Column(name = "learningprogrammequal")
	public Integer getLearningprogrammequal() {
		return this.learningprogrammequal;
	}

	/**
	 * Sets the learningprogrammequal.
	 *
	 * @param learningprogrammequal
	 *            the new learningprogrammequal
	 */
	public void setLearningprogrammequal(Integer learningprogrammequal) {
		this.learningprogrammequal = learningprogrammequal;
	}

	/**
	 * Gets the nqfleveldescription.
	 *
	 * @return the nqfleveldescription
	 */
	@Column(name = "nqfleveldescription")
	public String getNqfleveldescription() {
		return this.nqfleveldescription;
	}

	/**
	 * Sets the nqfleveldescription.
	 *
	 * @param nqfleveldescription
	 *            the new nqfleveldescription
	 */
	public void setNqfleveldescription(String nqfleveldescription) {
		this.nqfleveldescription = nqfleveldescription;
	}

	/**
	 * Gets the nqflevelg 2 description.
	 *
	 * @return the nqflevelg 2 description
	 */
	@Column(name = "nqflevelg2DESCRIPTION")
	public String getNqflevelg2description() {
		return this.nqflevelg2description;
	}

	/**
	 * Sets the nqflevelg 2 description.
	 *
	 * @param nqflevelg2description
	 *            the new nqflevelg 2 description
	 */
	public void setNqflevelg2description(String nqflevelg2description) {
		this.nqflevelg2description = nqflevelg2description;
	}

	/**
	 * Gets the providercode.
	 *
	 * @return the providercode
	 */
	@Column(name = "providercode")
	public String getProvidercode() {
		return this.providercode;
	}

	/**
	 * Sets the providercode.
	 *
	 * @param providercode
	 *            the new providercode
	 */
	public void setProvidercode(String providercode) {
		this.providercode = providercode;
	}

	/**
	 * Gets the provideretqaid.
	 *
	 * @return the provideretqaid
	 */
	@Column(name = "provideretqaid")
	public Integer getProvideretqaid() {
		return this.provideretqaid;
	}

	/**
	 * Sets the provideretqaid.
	 *
	 * @param provideretqaid
	 *            the new provideretqaid
	 */
	public void setProvideretqaid(Integer provideretqaid) {
		this.provideretqaid = provideretqaid;
	}

	/**
	 * Gets the providername.
	 *
	 * @return the providername
	 */
	@Column(name = "providername")
	public String getProvidername() {
		return this.providername;
	}

	/**
	 * Sets the providername.
	 *
	 * @param providername
	 *            the new providername
	 */
	public void setProvidername(String providername) {
		this.providername = providername;
	}

	/**
	 * Gets the qualarticulationoptions.
	 *
	 * @return the qualarticulationoptions
	 */
	@Column(name = "qualarticulationoptions")
	public String getQualarticulationoptions() {
		return this.qualarticulationoptions;
	}

	/**
	 * Sets the qualarticulationoptions.
	 *
	 * @param qualarticulationoptions
	 *            the new qualarticulationoptions
	 */
	public void setQualarticulationoptions(String qualarticulationoptions) {
		this.qualarticulationoptions = qualarticulationoptions;
	}

	/**
	 * Gets the qualassessorcriteria.
	 *
	 * @return the qualassessorcriteria
	 */
	@Column(name = "qualassessorcriteria")
	public String getQualassessorcriteria() {
		return this.qualassessorcriteria;
	}

	/**
	 * Sets the qualassessorcriteria.
	 *
	 * @param qualassessorcriteria
	 *            the new qualassessorcriteria
	 */
	public void setQualassessorcriteria(String qualassessorcriteria) {
		this.qualassessorcriteria = qualassessorcriteria;
	}

	/**
	 * Gets the qualificationclassdesc.
	 *
	 * @return the qualificationclassdesc
	 */
	@Column(name = "qualificationclassdesc")
	public String getQualificationclassdesc() {
		return this.qualificationclassdesc;
	}

	/**
	 * Sets the qualificationclassdesc.
	 *
	 * @param qualificationclassdesc
	 *            the new qualificationclassdesc
	 */
	public void setQualificationclassdesc(String qualificationclassdesc) {
		this.qualificationclassdesc = qualificationclassdesc;
	}

	/**
	 * Gets the qualificationid.
	 *
	 * @return the qualificationid
	 */
	@Column(name = "qualificationid")
	public Integer getQualificationid() {
		return this.qualificationid;
	}

	/**
	 * Sets the qualificationid.
	 *
	 * @param qualificationid
	 *            the new qualificationid
	 */
	public void setQualificationid(Integer qualificationid) {
		this.qualificationid = qualificationid;
	}

	/**
	 * Gets the qualificationminimumcredits.
	 *
	 * @return the qualificationminimumcredits
	 */
	@Column(name = "qualificationminimumcredits")
	public Integer getQualificationminimumcredits() {
		return this.qualificationminimumcredits;
	}

	/**
	 * Sets the qualificationminimumcredits.
	 *
	 * @param qualificationminimumcredits
	 *            the new qualificationminimumcredits
	 */
	public void setQualificationminimumcredits(Integer qualificationminimumcredits) {
		this.qualificationminimumcredits = qualificationminimumcredits;
	}

	/**
	 * Gets the qualificationnotes.
	 *
	 * @return the qualificationnotes
	 */
	@Column(name = "qualificationnotes")
	public String getQualificationnotes() {
		return this.qualificationnotes;
	}

	/**
	 * Sets the qualificationnotes.
	 *
	 * @param qualificationnotes
	 *            the new qualificationnotes
	 */
	public void setQualificationnotes(String qualificationnotes) {
		this.qualificationnotes = qualificationnotes;
	}

	/**
	 * Gets the qualificationpurpose.
	 *
	 * @return the qualificationpurpose
	 */
	@Column(name = "qualificationpurpose")
	public String getQualificationpurpose() {
		return this.qualificationpurpose;
	}

	/**
	 * Sets the qualificationpurpose.
	 *
	 * @param qualificationpurpose
	 *            the new qualificationpurpose
	 */
	public void setQualificationpurpose(String qualificationpurpose) {
		this.qualificationpurpose = qualificationpurpose;
	}

	/**
	 * Gets the qualificationtitle.
	 *
	 * @return the qualificationtitle
	 */
	@Column(name = "qualificationtitle")
	public String getQualificationtitle() {
		return this.qualificationtitle;
	}

	/**
	 * Sets the qualificationtitle.
	 *
	 * @param qualificationtitle
	 *            the new qualificationtitle
	 */
	public void setQualificationtitle(String qualificationtitle) {
		this.qualificationtitle = qualificationtitle;
	}

	/**
	 * Gets the qualificationtypedesc.
	 *
	 * @return the qualificationtypedesc
	 */
	@Column(name = "qualificationtypedesc")
	public String getQualificationtypedesc() {
		return this.qualificationtypedesc;
	}

	/**
	 * Sets the qualificationtypedesc.
	 *
	 * @param qualificationtypedesc
	 *            the new qualificationtypedesc
	 */
	public void setQualificationtypedesc(String qualificationtypedesc) {
		this.qualificationtypedesc = qualificationtypedesc;
	}

	/**
	 * Gets the qualificationtypeid.
	 *
	 * @return the qualificationtypeid
	 */
	@Column(name = "qualificationtypeid")
	public String getQualificationtypeid() {
		return this.qualificationtypeid;
	}

	/**
	 * Sets the qualificationtypeid.
	 *
	 * @param qualificationtypeid
	 *            the new qualificationtypeid
	 */
	public void setQualificationtypeid(String qualificationtypeid) {
		this.qualificationtypeid = qualificationtypeid;
	}

	/**
	 * Gets the qualintlbenchmarkingmemo.
	 *
	 * @return the qualintlbenchmarkingmemo
	 */
	@Column(name = "qualintlbenchmarkingmemo")
	public String getQualintlbenchmarkingmemo() {
		return this.qualintlbenchmarkingmemo;
	}

	/**
	 * Sets the qualintlbenchmarkingmemo.
	 *
	 * @param qualintlbenchmarkingmemo
	 *            the new qualintlbenchmarkingmemo
	 */
	public void setQualintlbenchmarkingmemo(String qualintlbenchmarkingmemo) {
		this.qualintlbenchmarkingmemo = qualintlbenchmarkingmemo;
	}

	/**
	 * Gets the quallearningassumedinplace.
	 *
	 * @return the quallearningassumedinplace
	 */
	@Column(name = "quallearningassumedinplace")
	public String getQuallearningassumedinplace() {
		return this.quallearningassumedinplace;
	}

	/**
	 * Sets the quallearningassumedinplace.
	 *
	 * @param quallearningassumedinplace
	 *            the new quallearningassumedinplace
	 */
	public void setQuallearningassumedinplace(String quallearningassumedinplace) {
		this.quallearningassumedinplace = quallearningassumedinplace;
	}

	/**
	 * Gets the qualmoderationoptions.
	 *
	 * @return the qualmoderationoptions
	 */
	@Column(name = "qualmoderationoptions")
	public String getQualmoderationoptions() {
		return this.qualmoderationoptions;
	}

	/**
	 * Sets the qualmoderationoptions.
	 *
	 * @param qualmoderationoptions
	 *            the new qualmoderationoptions
	 */
	public void setQualmoderationoptions(String qualmoderationoptions) {
		this.qualmoderationoptions = qualmoderationoptions;
	}

	/**
	 * Gets the qualrulesofcombination.
	 *
	 * @return the qualrulesofcombination
	 */
	@Column(name = "qualrulesofcombination")
	public String getQualrulesofcombination() {
		return this.qualrulesofcombination;
	}

	/**
	 * Sets the qualrulesofcombination.
	 *
	 * @param qualrulesofcombination
	 *            the new qualrulesofcombination
	 */
	public void setQualrulesofcombination(String qualrulesofcombination) {
		this.qualrulesofcombination = qualrulesofcombination;
	}

	/**
	 * Gets the recognizeprevlearningflag.
	 *
	 * @return the recognizeprevlearningflag
	 */
	@Column(name = "recognizeprevlearningflag")
	public String getRecognizeprevlearningflag() {
		return this.recognizeprevlearningflag;
	}

	/**
	 * Sets the recognizeprevlearningflag.
	 *
	 * @param recognizeprevlearningflag
	 *            the new recognizeprevlearningflag
	 */
	public void setRecognizeprevlearningflag(String recognizeprevlearningflag) {
		this.recognizeprevlearningflag = recognizeprevlearningflag;
	}

	/**
	 * Gets the registrationstatusdesc.
	 *
	 * @return the registrationstatusdesc
	 */
	@Column(name = "registrationstatusdesc")
	public String getRegistrationstatusdesc() {
		return this.registrationstatusdesc;
	}

	/**
	 * Sets the registrationstatusdesc.
	 *
	 * @param registrationstatusdesc
	 *            the new registrationstatusdesc
	 */
	public void setRegistrationstatusdesc(String registrationstatusdesc) {
		this.registrationstatusdesc = registrationstatusdesc;
	}

	/**
	 * Gets the registrationstatuscode.
	 *
	 * @return the registrationstatuscode
	 */
	@Column(name = "registrationstatuscode")
	public String getRegistrationstatuscode() {
		return this.registrationstatuscode;
	}

	/**
	 * Sets the registrationstatuscode.
	 *
	 * @param registrationstatuscode
	 *            the new registrationstatuscode
	 */
	public void setRegistrationstatuscode(String registrationstatuscode) {
		this.registrationstatuscode = registrationstatuscode;
	}

	/**
	 * Gets the saqadecisionnumber.
	 *
	 * @return the saqadecisionnumber
	 */
	@Column(name = "saqadecisionnumber")
	public String getSaqadecisionnumber() {
		return this.saqadecisionnumber;
	}

	/**
	 * Sets the saqadecisionnumber.
	 *
	 * @param saqadecisionnumber
	 *            the new saqadecisionnumber
	 */
	public void setSaqadecisionnumber(String saqadecisionnumber) {
		this.saqadecisionnumber = saqadecisionnumber;
	}

	/**
	 * Gets the sgbname.
	 *
	 * @return the sgbname
	 */
	@Column(name = "sgbname")
	public String getSgbname() {
		return this.sgbname;
	}

	/**
	 * Sets the sgbname.
	 *
	 * @param sgbname
	 *            the new sgbname
	 */
	public void setSgbname(String sgbname) {
		this.sgbname = sgbname;
	}

	/**
	 * Gets the subfielddescription.
	 *
	 * @return the subfielddescription
	 */
	@Column(name = "subfielddescription")
	public String getSubfielddescription() {
		return this.subfielddescription;
	}

	/**
	 * Sets the subfielddescription.
	 *
	 * @param subfielddescription
	 *            the new subfielddescription
	 */
	public void setSubfielddescription(String subfielddescription) {
		this.subfielddescription = subfielddescription;
	}

	/**
	 * Gets the trainoutperiod.
	 *
	 * @return the trainoutperiod
	 */
	@Column(name = "trainoutperiod")
	public Integer getTrainoutperiod() {
		return this.trainoutperiod;
	}

	/**
	 * Sets the trainoutperiod.
	 *
	 * @param trainoutperiod
	 *            the new trainoutperiod
	 */
	public void setTrainoutperiod(Integer trainoutperiod) {
		this.trainoutperiod = trainoutperiod;
	}

	/**
	 * Gets the transitionperiod.
	 *
	 * @return the transitionperiod
	 */
	@Column(name = "transitionperiod")
	public Integer getTransitionperiod() {
		return this.transitionperiod;
	}

	/**
	 * Sets the transitionperiod.
	 *
	 * @param transitionperiod
	 *            the new transitionperiod
	 */
	public void setTransitionperiod(Integer transitionperiod) {
		this.transitionperiod = transitionperiod;
	}

	/**
	 * Gets the saqa us qualifications.
	 *
	 * @return the saqa us qualifications
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "saqaQualification")
	public Set<SaqaUsQualification> getSaqaUsQualifications() {
		return this.saqaUsQualifications;
	}

	/**
	 * Sets the saqa us qualifications.
	 *
	 * @param saqaUsQualifications
	 *            the new saqa us qualifications
	 */
	public void setSaqaUsQualifications(Set<SaqaUsQualification> saqaUsQualifications) {
		this.saqaUsQualifications = saqaUsQualifications;
	}

	/**
	 * Gets the etqaid.
	 *
	 * @return the etqaid
	 */
	public String getEtqaid() {
		return etqaid;
	}

	/**
	 * Sets the etqaid.
	 *
	 * @param etqaid
	 *            the new etqaid
	 */
	public void setEtqaid(String etqaid) {
		this.etqaid = etqaid;
	}

	/**
	 * Gets the nqflevel.
	 *
	 * @return the nqflevel
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nqf_level_id", nullable = true)
	@Fetch(FetchMode.JOIN)

	public NqfLevels getNqflevel() {
		return nqflevel;
	}

	/**
	 * Sets the nqflevel.
	 *
	 * @param nqflevel
	 *            the new nqflevel
	 */
	public void setNqflevel(NqfLevels nqflevel) {
		this.nqflevel = nqflevel;
	}

	/**
	 * Gets the nqflevel id.
	 *
	 * @return the nqflevel id
	 */
	public String getNqflevelId() {
		return nqflevelId;
	}

	/**
	 * Sets the nqflevel id.
	 *
	 * @param nqflevelId
	 *            the new nqflevel id
	 */
	public void setNqflevelId(String nqflevelId) {
		this.nqflevelId = nqflevelId;
	}

	@Column(name = "workplace_approval_required", columnDefinition = "BIT default false")
	public Boolean getWorkplaceApprovalRequired() {
		return workplaceApprovalRequired;
	}

	public void setWorkplaceApprovalRequired(Boolean workplaceApprovalRequired) {
		this.workplaceApprovalRequired = workplaceApprovalRequired;
	}

	public Date getLastDateForEnrolment() {
		return lastDateForEnrolment;
	}

	public void setLastDateForEnrolment(Date lastDateForEnrolment) {
		this.lastDateForEnrolment = lastDateForEnrolment;
	}

	public Date getLastdateforachievement() {
		return lastdateforachievement;
	}

	public void setLastdateforachievement(Date lastdateforachievement) {
		this.lastdateforachievement = lastdateforachievement;
	}

	public Date getQualregistrationstartDate() {
		return qualregistrationstartDate;
	}

	public void setQualregistrationstartDate(Date qualregistrationstartDate) {
		this.qualregistrationstartDate = qualregistrationstartDate;
	}

	public Date getQualregistrationendDate() {
		return qualregistrationendDate;
	}

	public void setQualregistrationendDate(Date qualregistrationendDate) {
		this.qualregistrationendDate = qualregistrationendDate;
	}

	/**
	 * Gets the qualificationclassdesc.
	 *
	 * @return the qualificationclassdesc
	 */
	@Column(name = "qualificationid_string")
	public String getQualificationidString() {
		return this.qualificationidString;
	}

	/**
	 * Sets the qualificationclassdesc.
	 *
	 * @param qualificationclassdesc
	 *            the new qualificationclassdesc
	 */
	public void setQualificationidString(String qualificationidString) {
		this.qualificationidString = qualificationidString;
	}

	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	@JoinColumn(name = "designated_trade_id", nullable = true)
	public DesignatedTrade getDesignatedTrade() {
		return designatedTrade;
	}

	public void setDesignatedTrade(DesignatedTrade designatedTrade) {
		this.designatedTrade = designatedTrade;
	}

	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@ManyToOne(fetch = FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	@JoinColumn(name = "learner_mentor_ratio_id", nullable = true)
	public LearnerMentorRatio getLearnerMentorRatio() {
		return learnerMentorRatio;
	}

	public void setLearnerMentorRatio(LearnerMentorRatio learnerMentorRatio) {
		this.learnerMentorRatio = learnerMentorRatio;
	}

	@Column(name = "level_one")
	public Integer getLevelOne() {
		return levelOne;
	}

	public void setLevelOne(Integer levelOne) {
		this.levelOne = levelOne;
	}

	@Column(name = "level_two")
	public Integer getLevelTwo() {
		return levelTwo;
	}

	public void setLevelTwo(Integer levelTwo) {
		this.levelTwo = levelTwo;
	}

	@Column(name = "level_three")
	public Integer getLevelThree() {
		return levelThree;
	}

	public void setLevelThree(Integer levelThree) {
		this.levelThree = levelThree;
	}

	@Column(name = "level_four")
	public Integer getLevelFour() {
		return levelFour;
	}

	public void setLevelFour(Integer levelFour) {
		this.levelFour = levelFour;
	}

}