
package com.microsoft.schemas.dynamics.gp._2006._01;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "DynamicsGP", targetNamespace = "http://schemas.microsoft.com/dynamics/gp/2006/01", wsdlLocation = "file:/Users/hendrik/Desktop/DynamicsGP.wsdl")
@WebServiceClient(name = "DynamicsGP", targetNamespace = "http://schemas.microsoft.com/dynamics/gp/2006/01", wsdlLocation = "file:/src/main/webapp/wsdl/DynamicsGP.wsdl")
public class DynamicsGP_Service
    extends Service
{

    private final static URL DYNAMICSGP_WSDL_LOCATION;
    private final static WebServiceException DYNAMICSGP_EXCEPTION;
    private final static QName DYNAMICSGP_QNAME = new QName("http://schemas.microsoft.com/dynamics/gp/2006/01", "DynamicsGP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/Users/wesleypirie/Documents/Bitbucket/merSETA/MerSETA/src/main/webapp/wsdl/DynamicsGP.wsdl");
            url = new URL("file:/Users/hendrik/Documents/bitbucket/mersetaweb/MerSETA/src/main/webapp/wsdl/DynamicsGP.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DYNAMICSGP_WSDL_LOCATION = url;
        DYNAMICSGP_EXCEPTION = e;
    }

    public DynamicsGP_Service() {
        super(__getWsdlLocation(), DYNAMICSGP_QNAME);
    }

    public DynamicsGP_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DYNAMICSGP_QNAME, features);
    }

    public DynamicsGP_Service(URL wsdlLocation) {
        super(wsdlLocation, DYNAMICSGP_QNAME);
    }

    public DynamicsGP_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DYNAMICSGP_QNAME, features);
    }

    public DynamicsGP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DynamicsGP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DynamicsGP
     */
    @WebEndpoint(name = "LegacyDynamicsGP")
    public DynamicsGP getLegacyDynamicsGP() {
        return super.getPort(new QName("http://schemas.microsoft.com/dynamics/gp/2006/01", "LegacyDynamicsGP"), DynamicsGP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DynamicsGP
     */
    @WebEndpoint(name = "LegacyDynamicsGP")
    public DynamicsGP getLegacyDynamicsGP(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/dynamics/gp/2006/01", "LegacyDynamicsGP"), DynamicsGP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DYNAMICSGP_EXCEPTION!= null) {
            throw DYNAMICSGP_EXCEPTION;
        }
        return DYNAMICSGP_WSDL_LOCATION;
    }

}
