package haj.com.entity;
// Generated 04-May-2013 14:13:41 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * NqfLevel generated by hbm2java.
 */
@Entity
@Table(name = "municipality_type"

)
public class MunicipalityType implements IDataEntity {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	/**
	 * The municipality type desc. This field is required May not start with space
	 * Maximum length = 100 Uppercase value in field may only contain characters
	 * ABCDEFGHIJKLMNOPQRTSUVWXYZ1234567890@#&+() /\:._,`'
	 */
	@NotEmpty(message = "Enter municipality description")
	@Size(min = 1, max = 100, message = "Municipality description can't be more than 100 characters")
	@Column(name = "municipality_type_desc", length = 100)
	private String municipalityTypeDesc;

	/**
	 * The sic code. Field must contain a valid SIC_Code
	 */
	@Column(name = "sic_code", length = 20)
	private String sicCode;

	/** The create date. */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;

	/**
	 * Instantiates a new municipality type.
	 */
	public MunicipalityType() {
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id
	 *            the new id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the municipality type desc.
	 *
	 * @return the municipality type desc
	 */
	public String getMunicipalityTypeDesc() {
		return municipalityTypeDesc;
	}

	/**
	 * Sets the municipality type desc.
	 *
	 * @param municipalityTypeDesc
	 *            the new municipality type desc
	 */
	public void setMunicipalityTypeDesc(String municipalityTypeDesc) {
		this.municipalityTypeDesc = municipalityTypeDesc;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "\n MunicipalityType [id=" + id + ", municipalityTypeDesc=" + municipalityTypeDesc + "]";
	}

	/**
	 * Gets the sic code.
	 *
	 * @return the sic code
	 */
	public String getSicCode() {
		return sicCode;
	}

	/**
	 * Sets the sic code.
	 *
	 * @param sicCode
	 *            the new sic code
	 */
	public void setSicCode(String sicCode) {
		this.sicCode = sicCode;
	}

	/**
	 * Gets the creates the date.
	 *
	 * @return the creates the date
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * Sets the creates the date.
	 *
	 * @param createDate
	 *            the new creates the date
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MunicipalityType other = (MunicipalityType) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
