package haj.com.entity;
// Generated 04-May-2013 14:13:41 by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * Province generated by hbm2java.
 */
@Entity
@Table(name="province"
   
)
public class Province  implements  IDataEntity
{
	  
  	/** The Constant serialVersionUID. */
  	private static final long serialVersionUID = 1L;

     /** The id. */
	private Long id;
     
     /** The province desc. */
     private String provinceDesc;
     
     /** The code. */
     private String code;
     
     /** The map. */
     private String map;
     
     /** The stats prov id. */
     private String statsProvId;
     
     /** The land area. */
     private String  landArea;
     
     /** The color. */
     private String color;
     
     /** The municipalities. */
     private Set<Municipality> municipalities = new HashSet<Municipality>(0);

	/** The create date. */
	private Date createDate;
    
    /**
     * Instantiates a new province.
     */
    public Province() {
    }

    /**
     * Instantiates a new province.
     *
     * @param provinceDesc the province desc
     * @param municipalities the municipalities
     */
    public Province(String provinceDesc, Set<Municipality> municipalities) {
       this.provinceDesc = provinceDesc;
       this.municipalities = municipalities;
    }
   
    
     /**
      * Instantiates a new province.
      *
      * @param id the id
      */
	public Province(Long id) {
		super();
		this.id = id;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
	public Long getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     *
     * @param id the new id
     */
	public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * Gets the province desc.
     *
     * @return the province desc
     */
    @Column(name="province_desc", length=50)
    public String getProvinceDesc() {
        return this.provinceDesc;
    }
    
    /**
     * Sets the province desc.
     *
     * @param provinceDesc the new province desc
     */
    public void setProvinceDesc(String provinceDesc) {
        this.provinceDesc = provinceDesc;
    }

/**
 * Gets the municipalities.
 *
 * @return the municipalities
 */
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="province")
    public Set<Municipality> getMunicipalities() {
        return this.municipalities;
    }
    
    /**
     * Sets the municipalities.
     *
     * @param municipalities the new municipalities
     */
    public void setMunicipalities(Set<Municipality> municipalities) {
        this.municipalities = municipalities;
    }

    /**
     * Gets the code.
     *
     * @return the code
     */
    @Column(name="code", length=5)
	public String getCode() {
		return code;
	}

	/**
	 * Sets the code.
	 *
	 * @param code the new code
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * Gets the map.
	 *
	 * @return the map
	 */
	@Column(name="map", length=50)
	public String getMap() {
		return map;
	}

	/**
	 * Sets the map.
	 *
	 * @param map the new map
	 */
	public void setMap(String map) {
		this.map = map;
	}

	/**
	 * Gets the stats prov id.
	 *
	 * @return the stats prov id
	 */
	@Column(name="stats_prov_id")
	public String getStatsProvId() {
		return statsProvId;
	}

	/**
	 * Sets the stats prov id.
	 *
	 * @param statsProvId the new stats prov id
	 */
	public void setStatsProvId(String statsProvId) {
		this.statsProvId = statsProvId;
	}

	/**
	 * Gets the land area.
	 *
	 * @return the land area
	 */
	@Column(name="land_area")
	public String getLandArea() {
		return landArea;
	}

	/**
	 * Sets the land area.
	 *
	 * @param landArea the new land area
	 */
	public void setLandArea(String landArea) {
		this.landArea = landArea;
	}

	/**
	 * Gets the color.
	 *
	 * @return the color
	 */
	@Column(name="color", length=7)
	public String getColor() {
		return color;
	}

	/**
	 * Sets the color.
	 *
	 * @param color the new color
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Province other = (Province) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
    
    /**
     * Gets the creates the date.
     *
     * @return the creates the date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * Sets the creates the date.
	 *
	 * @param createDate the new creates the date
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}




}


