package haj.com.sars;
// Generated Oct 30, 2017 11:57:45 AM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import haj.com.entity.Doc;
import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * SarsLeviesPaid generated by hbm2java.
 */
@Entity
@Table(name="sars_levies_paid"
   
)
public class SarsLeviesPaid  implements IDataEntity {


     /** The id. */
     private Long id;
     
     /** The gl posting date. */
     private Date glPostingDate;
     
     /** The checkbook amount. */
     private BigDecimal checkbookAmount;
     
     /** The levy file. */
     private String levyFile;

     /** The levy file D. */
     private Date levyFileD;
     

 	private SarsFiles sarsFiles;
     
 	
 	private List<Doc> docs;
    /**
     * Instantiates a new sars levies paid.
     */
    public SarsLeviesPaid() {
    }


   
     /**
      * Gets the id.
      *
      * @return the id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     *
     * @param id the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the gl posting date.
     *
     * @return the gl posting date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gl_posting_date", length=19)
    public Date getGlPostingDate() {
        return this.glPostingDate;
    }
    
    /**
     * Sets the gl posting date.
     *
     * @param glPostingDate the new gl posting date
     */
    public void setGlPostingDate(Date glPostingDate) {
        this.glPostingDate = glPostingDate;
    }

    
    /**
     * Gets the checkbook amount.
     *
     * @return the checkbook amount
     */
    @Column(name="checkbook_amount", columnDefinition = "DOUBLE")
    public BigDecimal getCheckbookAmount() {
        return this.checkbookAmount;
    }
    
    /**
     * Sets the checkbook amount.
     *
     * @param checkbookAmount the new checkbook amount
     */
    public void setCheckbookAmount(BigDecimal checkbookAmount) {
        this.checkbookAmount = checkbookAmount;
    }

    
    /**
     * Gets the levy file.
     *
     * @return the levy file
     */
    @Column(name="levy_file", length=20)
    public String getLevyFile() {
        return this.levyFile;
    }
    
    /**
     * Sets the levy file.
     *
     * @param levyFile the new levy file
     */
    public void setLevyFile(String levyFile) {
        this.levyFile = levyFile;
    }



    /**
     * Gets the levy file D.
     *
     * @return the levy file D
     */
    @Transient
	public Date getLevyFileD() {
		return levyFileD;
	}



	/**
	 * Sets the levy file D.
	 *
	 * @param levyFileD the new levy file D
	 */
	public void setLevyFileD(Date levyFileD) {
		this.levyFileD = levyFileD;
	}


	@Transient
	public List<Doc> getDocs() {
		return docs;
	}



	public void setDocs(List<Doc> docs) {
		this.docs = docs;
	}


 	/** The sars files. */
 	@ManyToOne(fetch = FetchType.LAZY)
 	@JoinColumn(name = "sars_file_id", nullable = true)
	public SarsFiles getSarsFiles() {
		return sarsFiles;
	}



	public void setSarsFiles(SarsFiles sarsFiles) {
		this.sarsFiles = sarsFiles;
	}




}


