package haj.com.sars;
// Generated Dec 11, 2017 4:07:07 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import haj.com.framework.IDataEntity;

/**
 * SarsInterSetaTransferLevies generated by hbm2java
 */
@Entity
@Table(name="sars_inter_seta_transfer_levies"
   
)
public class SarsInterSetaTransferLevies  implements IDataEntity {


     private Long id;
     private String sdlnumber;
     private String organisationName;
     private String schemeYear;
     private String transactionType;
     private Double totalA;
     private Double t80Percent;
     private Integer relevantYear;
     private Integer relevantMonth;
     private String transferType;
     private String transactionDate;
     private String setaName;
     private String setaCode;
     private Double mandatory;
     private Double discretionary;
     private Double admin;
     private Double penalties;
     private Double interest;
     private Double total;

    public SarsInterSetaTransferLevies() {
    }

    public SarsInterSetaTransferLevies(String sdlnumber, String organisationName, String schemeYear, String transactionType, Double totalA, Double t80Percent, Integer relevantYear, Integer relevantMonth, String transferType, String transactionDate, String setaName, String setaCode, Double mandatory, Double discretionary, Double admin, Double penalties, Double interest, Double total) {
       this.sdlnumber = sdlnumber;
       this.organisationName = organisationName;
       this.schemeYear = schemeYear;
       this.transactionType = transactionType;
       this.totalA = totalA;
       this.t80Percent = t80Percent;
       this.relevantYear = relevantYear;
       this.relevantMonth = relevantMonth;
       this.transferType = transferType;
       this.transactionDate = transactionDate;
       this.setaName = setaName;
       this.setaCode = setaCode;
       this.mandatory = mandatory;
       this.discretionary = discretionary;
       this.admin = admin;
       this.penalties = penalties;
       this.interest = interest;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="sdlnumber")
    public String getSdlnumber() {
        return this.sdlnumber;
    }
    
    public void setSdlnumber(String sdlnumber) {
        this.sdlnumber = sdlnumber;
    }

    
    @Column(name="organisation_name")
    public String getOrganisationName() {
        return this.organisationName;
    }
    
    public void setOrganisationName(String organisationName) {
        this.organisationName = organisationName;
    }

    
    @Column(name="scheme_year")
    public String getSchemeYear() {
        return this.schemeYear;
    }
    
    public void setSchemeYear(String schemeYear) {
        this.schemeYear = schemeYear;
    }

    
    @Column(name="transaction_type")
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="total_a", precision=22, scale=0)
    public Double getTotalA() {
        return this.totalA;
    }
    
    public void setTotalA(Double totalA) {
        this.totalA = totalA;
    }

    
    @Column(name="t_80_percent", precision=22, scale=0)
    public Double getT80Percent() {
        return this.t80Percent;
    }
    
    public void setT80Percent(Double t80Percent) {
        this.t80Percent = t80Percent;
    }

    
    @Column(name="relevant_year")
    public Integer getRelevantYear() {
        return this.relevantYear;
    }
    
    public void setRelevantYear(Integer relevantYear) {
        this.relevantYear = relevantYear;
    }

    
    @Column(name="relevant_month")
    public Integer getRelevantMonth() {
        return this.relevantMonth;
    }
    
    public void setRelevantMonth(Integer relevantMonth) {
        this.relevantMonth = relevantMonth;
    }

    
    @Column(name="transfer_type")
    public String getTransferType() {
        return this.transferType;
    }
    
    public void setTransferType(String transferType) {
        this.transferType = transferType;
    }

    
    @Column(name="transaction_date")
    public String getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="seta_name")
    public String getSetaName() {
        return this.setaName;
    }
    
    public void setSetaName(String setaName) {
        this.setaName = setaName;
    }

    
    @Column(name="seta_code")
    public String getSetaCode() {
        return this.setaCode;
    }
    
    public void setSetaCode(String setaCode) {
        this.setaCode = setaCode;
    }

    
    @Column(name="mandatory", precision=22, scale=0)
    public Double getMandatory() {
        return this.mandatory;
    }
    
    public void setMandatory(Double mandatory) {
        this.mandatory = mandatory;
    }

    
    @Column(name="discretionary", precision=22, scale=0)
    public Double getDiscretionary() {
        return this.discretionary;
    }
    
    public void setDiscretionary(Double discretionary) {
        this.discretionary = discretionary;
    }

    
    @Column(name="admin", precision=22, scale=0)
    public Double getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Double admin) {
        this.admin = admin;
    }

    
    @Column(name="penalties", precision=22, scale=0)
    public Double getPenalties() {
        return this.penalties;
    }
    
    public void setPenalties(Double penalties) {
        this.penalties = penalties;
    }

    
    @Column(name="interest", precision=22, scale=0)
    public Double getInterest() {
        return this.interest;
    }
    
    public void setInterest(Double interest) {
        this.interest = interest;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


