package haj.com.entity;
// Generated Nov 2, 2017 11:33:16 AM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * Tempx generated by hbm2java.
 */

@NamedQueries({
	@NamedQuery(
	name = "NQ_allTempX",
	query = "select o from Tempx o"
	)
})
@NamedNativeQueries({
	@NamedNativeQuery(
	name = "NQ_NATIVE_allTempX",
	query = "select * from tempx",
        resultClass = Tempx.class
	),
	@NamedNativeQuery(
			name = "NQ_NATIVE_findBySDLnumber",
			query = "select * from tempx where SDLNUMBER = :sdlnumber ",
		        resultClass = Tempx.class
			)
	
})
@Entity
@Table(name="tempx"
   
)
public class Tempx  implements IDataEntity {


     /** The id. */
     private Long id;
     
     /** The sdlnumber. */
     private String sdlnumber;
     
     /** The vendor name. */
     private String vendorName;
     
     /** The transaction date. */
     private String transactionDate;
     
     /** The financial year. */
     private Integer financialYear;
     
     /** The levy year 3. */
     private Integer levyYear3;
     
     /** The document type. */
     private String documentType;
     
     /** The ref voucher number 4. */
     private String refVoucherNumber4;
     
     /** The main account number 5. */
     private String mainAccountNumber5;
     
     /** The main account value 6. */
     private String mainAccountValue6;
     
     /** The main account type 7. */
     private String mainAccountType7;
     
     /** The contra account number 8. */
     private String contraAccountNumber8;
     
     /** The contra value 9. */
     private String contraValue9;
     
     /** The contra type 10. */
     private String contraType10;
     
     /** The creditor id 11. */
     private String creditorId11;
     
     /** The document number 12. */
     private String documentNumber12;
     
     /** The posting status 13. */
     private String postingStatus13;
     
     /** The posting date. */
     private String postingDate;
     
     /** The payment status. */
     private String paymentStatus;
     
     /** The transaction description. */
     private String transactionDescription;
     
     /** The trx source. */
     private String trxSource;
     
     /** The batch number. */
     private String batchNumber;
     
     /** The grant type. */
     private String grantType;
     
     /** The chamber. */
     private String chamber;
     
     /** The chamber code. */
     private Integer chamberCode;
     
     /** The xxx. */
     private String xxx;
     
     /** The document amount. */
     private String documentAmount;
     
     /** The current transaction amount. */
     private String currentTransactionAmount;
     
     /** The diff. */
     private String diff;
     
     /** The converted. */
     private Boolean converted;

    /**
     * Instantiates a new tempx.
     */
    public Tempx() {
    }

    /**
     * Instantiates a new tempx.
     *
     * @param sdlnumber the sdlnumber
     * @param vendorName the vendor name
     * @param transactionDate the transaction date
     * @param financialYear the financial year
     * @param levyYear3 the levy year 3
     * @param documentType the document type
     * @param refVoucherNumber4 the ref voucher number 4
     * @param mainAccountNumber5 the main account number 5
     * @param mainAccountValue6 the main account value 6
     * @param mainAccountType7 the main account type 7
     * @param contraAccountNumber8 the contra account number 8
     * @param contraValue9 the contra value 9
     * @param contraType10 the contra type 10
     * @param creditorId11 the creditor id 11
     * @param documentNumber12 the document number 12
     * @param postingStatus13 the posting status 13
     * @param postingDate the posting date
     * @param paymentStatus the payment status
     * @param transactionDescription the transaction description
     * @param trxSource the trx source
     * @param batchNumber the batch number
     * @param grantType the grant type
     * @param chamber the chamber
     * @param chamberCode the chamber code
     * @param xxx the xxx
     * @param documentAmount the document amount
     * @param currentTransactionAmount the current transaction amount
     * @param diff the diff
     */
    public Tempx(String sdlnumber, String vendorName, String transactionDate, Integer financialYear, Integer levyYear3, String documentType, String refVoucherNumber4, String mainAccountNumber5, String mainAccountValue6, String mainAccountType7, String contraAccountNumber8, String contraValue9, String contraType10, String creditorId11, String documentNumber12, String postingStatus13, String postingDate, String paymentStatus, String transactionDescription, String trxSource, String batchNumber, String grantType, String chamber, Integer chamberCode, String xxx, String documentAmount, String currentTransactionAmount, String diff) {
       this.sdlnumber = sdlnumber;
       this.vendorName = vendorName;
       this.transactionDate = transactionDate;
       this.financialYear = financialYear;
       this.levyYear3 = levyYear3;
       this.documentType = documentType;
       this.refVoucherNumber4 = refVoucherNumber4;
       this.mainAccountNumber5 = mainAccountNumber5;
       this.mainAccountValue6 = mainAccountValue6;
       this.mainAccountType7 = mainAccountType7;
       this.contraAccountNumber8 = contraAccountNumber8;
       this.contraValue9 = contraValue9;
       this.contraType10 = contraType10;
       this.creditorId11 = creditorId11;
       this.documentNumber12 = documentNumber12;
       this.postingStatus13 = postingStatus13;
       this.postingDate = postingDate;
       this.paymentStatus = paymentStatus;
       this.transactionDescription = transactionDescription;
       this.trxSource = trxSource;
       this.batchNumber = batchNumber;
       this.grantType = grantType;
       this.chamber = chamber;
       this.chamberCode = chamberCode;
       this.xxx = xxx;
       this.documentAmount = documentAmount;
       this.currentTransactionAmount = currentTransactionAmount;
       this.diff = diff;
    }
   
     /**
      * Gets the id.
      *
      * @return the id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     *
     * @param id the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    
    /**
     * Gets the sdlnumber.
     *
     * @return the sdlnumber
     */
    @Column(name="SDLNUMBER")
    public String getSdlnumber() {
        return this.sdlnumber;
    }
    
    /**
     * Sets the sdlnumber.
     *
     * @param sdlnumber the new sdlnumber
     */
    public void setSdlnumber(String sdlnumber) {
        this.sdlnumber = sdlnumber;
    }

    
    /**
     * Gets the vendor name.
     *
     * @return the vendor name
     */
    @Column(name="VendorName")
    public String getVendorName() {
        return this.vendorName;
    }
    
    /**
     * Sets the vendor name.
     *
     * @param vendorName the new vendor name
     */
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    
    /**
     * Gets the transaction date.
     *
     * @return the transaction date
     */
    @Column(name="Transaction_date")
    public String getTransactionDate() {
        return this.transactionDate;
    }
    
    /**
     * Sets the transaction date.
     *
     * @param transactionDate the new transaction date
     */
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    /**
     * Gets the financial year.
     *
     * @return the financial year
     */
    @Column(name="Financial_year")
    public Integer getFinancialYear() {
        return this.financialYear;
    }
    
    /**
     * Sets the financial year.
     *
     * @param financialYear the new financial year
     */
    public void setFinancialYear(Integer financialYear) {
        this.financialYear = financialYear;
    }

    
    /**
     * Gets the levy year 3.
     *
     * @return the levy year 3
     */
    @Column(name="Levy_Year_3")
    public Integer getLevyYear3() {
        return this.levyYear3;
    }
    
    /**
     * Sets the levy year 3.
     *
     * @param levyYear3 the new levy year 3
     */
    public void setLevyYear3(Integer levyYear3) {
        this.levyYear3 = levyYear3;
    }

    
    /**
     * Gets the document type.
     *
     * @return the document type
     */
    @Column(name="Document_Type")
    public String getDocumentType() {
        return this.documentType;
    }
    
    /**
     * Sets the document type.
     *
     * @param documentType the new document type
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    
    /**
     * Gets the ref voucher number 4.
     *
     * @return the ref voucher number 4
     */
    @Column(name="Ref_Voucher_Number_4")
    public String getRefVoucherNumber4() {
        return this.refVoucherNumber4;
    }
    
    /**
     * Sets the ref voucher number 4.
     *
     * @param refVoucherNumber4 the new ref voucher number 4
     */
    public void setRefVoucherNumber4(String refVoucherNumber4) {
        this.refVoucherNumber4 = refVoucherNumber4;
    }

    
    /**
     * Gets the main account number 5.
     *
     * @return the main account number 5
     */
    @Column(name="Main_account_number_5")
    public String getMainAccountNumber5() {
        return this.mainAccountNumber5;
    }
    
    /**
     * Sets the main account number 5.
     *
     * @param mainAccountNumber5 the new main account number 5
     */
    public void setMainAccountNumber5(String mainAccountNumber5) {
        this.mainAccountNumber5 = mainAccountNumber5;
    }

    
    /**
     * Gets the main account value 6.
     *
     * @return the main account value 6
     */
    @Column(name="Main_Account_Value_6_")
    public String getMainAccountValue6() {
        return this.mainAccountValue6;
    }
    
    /**
     * Sets the main account value 6.
     *
     * @param mainAccountValue6 the new main account value 6
     */
    public void setMainAccountValue6(String mainAccountValue6) {
        this.mainAccountValue6 = mainAccountValue6;
    }

    
    /**
     * Gets the main account type 7.
     *
     * @return the main account type 7
     */
    @Column(name="Main_account_type_7_")
    public String getMainAccountType7() {
        return this.mainAccountType7;
    }
    
    /**
     * Sets the main account type 7.
     *
     * @param mainAccountType7 the new main account type 7
     */
    public void setMainAccountType7(String mainAccountType7) {
        this.mainAccountType7 = mainAccountType7;
    }

    
    /**
     * Gets the contra account number 8.
     *
     * @return the contra account number 8
     */
    @Column(name="Contra_account_number_8_")
    public String getContraAccountNumber8() {
        return this.contraAccountNumber8;
    }
    
    /**
     * Sets the contra account number 8.
     *
     * @param contraAccountNumber8 the new contra account number 8
     */
    public void setContraAccountNumber8(String contraAccountNumber8) {
        this.contraAccountNumber8 = contraAccountNumber8;
    }

    
    /**
     * Gets the contra value 9.
     *
     * @return the contra value 9
     */
    @Column(name="Contra_Value_9_")
    public String getContraValue9() {
        return this.contraValue9;
    }
    
    /**
     * Sets the contra value 9.
     *
     * @param contraValue9 the new contra value 9
     */
    public void setContraValue9(String contraValue9) {
        this.contraValue9 = contraValue9;
    }

    
    /**
     * Gets the contra type 10.
     *
     * @return the contra type 10
     */
    @Column(name="Contra_type_10_")
    public String getContraType10() {
        return this.contraType10;
    }
    
    /**
     * Sets the contra type 10.
     *
     * @param contraType10 the new contra type 10
     */
    public void setContraType10(String contraType10) {
        this.contraType10 = contraType10;
    }

    
    /**
     * Gets the creditor id 11.
     *
     * @return the creditor id 11
     */
    @Column(name="Creditor_ID_11_")
    public String getCreditorId11() {
        return this.creditorId11;
    }
    
    /**
     * Sets the creditor id 11.
     *
     * @param creditorId11 the new creditor id 11
     */
    public void setCreditorId11(String creditorId11) {
        this.creditorId11 = creditorId11;
    }

    
    /**
     * Gets the document number 12.
     *
     * @return the document number 12
     */
    @Column(name="Document_number_12")
    public String getDocumentNumber12() {
        return this.documentNumber12;
    }
    
    /**
     * Sets the document number 12.
     *
     * @param documentNumber12 the new document number 12
     */
    public void setDocumentNumber12(String documentNumber12) {
        this.documentNumber12 = documentNumber12;
    }

    
    /**
     * Gets the posting status 13.
     *
     * @return the posting status 13
     */
    @Column(name="Posting_status_13")
    public String getPostingStatus13() {
        return this.postingStatus13;
    }
    
    /**
     * Sets the posting status 13.
     *
     * @param postingStatus13 the new posting status 13
     */
    public void setPostingStatus13(String postingStatus13) {
        this.postingStatus13 = postingStatus13;
    }

    
    /**
     * Gets the posting date.
     *
     * @return the posting date
     */
    @Column(name="Posting_Date")
    public String getPostingDate() {
        return this.postingDate;
    }
    
    /**
     * Sets the posting date.
     *
     * @param postingDate the new posting date
     */
    public void setPostingDate(String postingDate) {
        this.postingDate = postingDate;
    }

    
    /**
     * Gets the payment status.
     *
     * @return the payment status
     */
    @Column(name="Payment_status")
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    /**
     * Sets the payment status.
     *
     * @param paymentStatus the new payment status
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    
    /**
     * Gets the transaction description.
     *
     * @return the transaction description
     */
    @Column(name="Transaction_Description")
    public String getTransactionDescription() {
        return this.transactionDescription;
    }
    
    /**
     * Sets the transaction description.
     *
     * @param transactionDescription the new transaction description
     */
    public void setTransactionDescription(String transactionDescription) {
        this.transactionDescription = transactionDescription;
    }

    
    /**
     * Gets the trx source.
     *
     * @return the trx source
     */
    @Column(name="TRX_Source")
    public String getTrxSource() {
        return this.trxSource;
    }
    
    /**
     * Sets the trx source.
     *
     * @param trxSource the new trx source
     */
    public void setTrxSource(String trxSource) {
        this.trxSource = trxSource;
    }

    
    /**
     * Gets the batch number.
     *
     * @return the batch number
     */
    @Column(name="Batch_Number")
    public String getBatchNumber() {
        return this.batchNumber;
    }
    
    /**
     * Sets the batch number.
     *
     * @param batchNumber the new batch number
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    
    /**
     * Gets the grant type.
     *
     * @return the grant type
     */
    @Column(name="Grant_type")
    public String getGrantType() {
        return this.grantType;
    }
    
    /**
     * Sets the grant type.
     *
     * @param grantType the new grant type
     */
    public void setGrantType(String grantType) {
        this.grantType = grantType;
    }

    
    /**
     * Gets the chamber.
     *
     * @return the chamber
     */
    @Column(name="Chamber")
    public String getChamber() {
        return this.chamber;
    }
    
    /**
     * Sets the chamber.
     *
     * @param chamber the new chamber
     */
    public void setChamber(String chamber) {
        this.chamber = chamber;
    }

    
    /**
     * Gets the chamber code.
     *
     * @return the chamber code
     */
    @Column(name="Chamber_code")
    public Integer getChamberCode() {
        return this.chamberCode;
    }
    
    /**
     * Sets the chamber code.
     *
     * @param chamberCode the new chamber code
     */
    public void setChamberCode(Integer chamberCode) {
        this.chamberCode = chamberCode;
    }

    
    /**
     * Gets the xxx.
     *
     * @return the xxx
     */
    @Column(name="xxx")
    public String getXxx() {
        return this.xxx;
    }
    
    /**
     * Sets the xxx.
     *
     * @param xxx the new xxx
     */
    public void setXxx(String xxx) {
        this.xxx = xxx;
    }

    
    /**
     * Gets the document amount.
     *
     * @return the document amount
     */
    @Column(name="_Document_amount_")
    public String getDocumentAmount() {
        return this.documentAmount;
    }
    
    /**
     * Sets the document amount.
     *
     * @param documentAmount the new document amount
     */
    public void setDocumentAmount(String documentAmount) {
        this.documentAmount = documentAmount;
    }

    
    /**
     * Gets the current transaction amount.
     *
     * @return the current transaction amount
     */
    @Column(name="Current_transaction_amount")
    public String getCurrentTransactionAmount() {
        return this.currentTransactionAmount;
    }
    
    /**
     * Sets the current transaction amount.
     *
     * @param currentTransactionAmount the new current transaction amount
     */
    public void setCurrentTransactionAmount(String currentTransactionAmount) {
        this.currentTransactionAmount = currentTransactionAmount;
    }

    
    /**
     * Gets the diff.
     *
     * @return the diff
     */
    @Column(name="DIFF")
    public String getDiff() {
        return this.diff;
    }
    
    /**
     * Sets the diff.
     *
     * @param diff the new diff
     */
    public void setDiff(String diff) {
        this.diff = diff;
    }

	/**
	 * Gets the converted.
	 *
	 * @return the converted
	 */
	public Boolean getConverted() {
		return converted;
	}

	/**
	 * Sets the converted.
	 *
	 * @param converted the new converted
	 */
	public void setConverted(Boolean converted) {
		this.converted = converted;
	}




}


