package haj.com.gptransations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransictionConverterSoap", targetNamespace = "http://Finance.merseta.org.za/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransictionConverterSoap {


    /**
     * 
     * @param password
     * @param vendid
     * @param username
     * @return
     *     returns com.vendor.transiction.ArrayOfInfo
     */
    @WebMethod(operationName = "OutStandingTransactions", action = "http://Finance.merseta.org.za/OutStandingTransactions")
    @WebResult(name = "OutStandingTransactionsResult", targetNamespace = "http://Finance.merseta.org.za/")
    @RequestWrapper(localName = "OutStandingTransactions", targetNamespace = "http://Finance.merseta.org.za/", className = "com.vendor.transiction.OutStandingTransactions")
    @ResponseWrapper(localName = "OutStandingTransactionsResponse", targetNamespace = "http://Finance.merseta.org.za/", className = "com.vendor.transiction.OutStandingTransactionsResponse")
    public ArrayOfInfo outStandingTransactions(
        @WebParam(name = "Username", targetNamespace = "http://Finance.merseta.org.za/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://Finance.merseta.org.za/")
        String password,
        @WebParam(name = "vendid", targetNamespace = "http://Finance.merseta.org.za/")
        String vendid);

    /**
     * 
     * @param password
     * @param vendid
     * @param username
     * @return
     *     returns com.vendor.transiction.ArrayOfRecentPayments
     */
    @WebMethod(operationName = "RecentTransactions", action = "http://Finance.merseta.org.za/RecentTransactions")
    @WebResult(name = "RecentTransactionsResult", targetNamespace = "http://Finance.merseta.org.za/")
    @RequestWrapper(localName = "RecentTransactions", targetNamespace = "http://Finance.merseta.org.za/", className = "com.vendor.transiction.RecentTransactions")
    @ResponseWrapper(localName = "RecentTransactionsResponse", targetNamespace = "http://Finance.merseta.org.za/", className = "com.vendor.transiction.RecentTransactionsResponse")
    public ArrayOfRecentPayments recentTransactions(
        @WebParam(name = "Username", targetNamespace = "http://Finance.merseta.org.za/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://Finance.merseta.org.za/")
        String password,
        @WebParam(name = "vendid", targetNamespace = "http://Finance.merseta.org.za/")
        String vendid);

}
