package haj.com.gptransations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransictionConverter", targetNamespace = "http://Finance.merseta.org.za/", wsdlLocation = "https://testgpws.merseta.org.za/TransictionConverter.asmx?WSDL")
public class TransictionConverter extends Service {

    private final static URL TRANSICTIONCONVERTER_WSDL_LOCATION;
    private final static WebServiceException TRANSICTIONCONVERTER_EXCEPTION;
    private final static QName TRANSICTIONCONVERTER_QNAME = new QName("http://Finance.merseta.org.za/", "TransictionConverter");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://testgpws.merseta.org.za/TransictionConverter.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSICTIONCONVERTER_WSDL_LOCATION = url;
        TRANSICTIONCONVERTER_EXCEPTION = e;
    }

    public TransictionConverter() {
        super(__getWsdlLocation(), TRANSICTIONCONVERTER_QNAME);
    }

    public TransictionConverter(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSICTIONCONVERTER_QNAME, features);
    }

    public TransictionConverter(URL wsdlLocation) {
        super(wsdlLocation, TRANSICTIONCONVERTER_QNAME);
    }

    public TransictionConverter(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSICTIONCONVERTER_QNAME, features);
    }

    public TransictionConverter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransictionConverter(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransictionConverterSoap
     */
    @WebEndpoint(name = "TransictionConverterSoap")
    public TransictionConverterSoap getTransictionConverterSoap() {
        return super.getPort(new QName("http://Finance.merseta.org.za/", "TransictionConverterSoap"), TransictionConverterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransictionConverterSoap
     */
    @WebEndpoint(name = "TransictionConverterSoap")
    public TransictionConverterSoap getTransictionConverterSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://Finance.merseta.org.za/", "TransictionConverterSoap"), TransictionConverterSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSICTIONCONVERTER_EXCEPTION!= null) {
            throw TRANSICTIONCONVERTER_EXCEPTION;
        }
        return TRANSICTIONCONVERTER_WSDL_LOCATION;
    }

}
