package haj.com.entity.datatakeon;
// Generated Oct 17, 2017 2:30:50 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import haj.com.framework.IDataEntity;

// TODO: Auto-generated Javadoc
/**
 * Unitstandard generated by hbm2java ONLY FOR DATA MIGRATION.
 */
@Entity
@Table(name="takeon_unitstandard" )
public class TakOnUnitstandard  implements IDataEntity {


     /** The id. */
     private Long id;
     
     /** The unit std code. */
     private Double unitStdCode;
     
     /** The unit std desc. */
     private String unitStdDesc;
     
     /** The nqflevel. */
     private String nqflevel;
     
     /** The credit value. */
     private Double creditValue;
     
     /** The saqaregistration date. */
     private Date saqaregistrationDate;
     
     /** The setaaccreditation date. */
     private Date setaaccreditationDate;
     
     /** The extension granted. */
     private String extensionGranted;
     
     /** The comments. */
     private String comments;

    /**
     * Instantiates a new tak on unitstandard.
     */
    public TakOnUnitstandard() {
    }

    /**
     * Instantiates a new tak on unitstandard.
     *
     * @param unitStdCode the unit std code
     * @param unitStdDesc the unit std desc
     * @param nqflevel the nqflevel
     * @param creditValue the credit value
     * @param saqaregistrationDate the saqaregistration date
     * @param setaaccreditationDate the setaaccreditation date
     * @param extensionGranted the extension granted
     * @param comments the comments
     */
    public TakOnUnitstandard(Double unitStdCode, String unitStdDesc, String nqflevel, Double creditValue, Date saqaregistrationDate, Date setaaccreditationDate, String extensionGranted, String comments) {
       this.unitStdCode = unitStdCode;
       this.unitStdDesc = unitStdDesc;
       this.nqflevel = nqflevel;
       this.creditValue = creditValue;
       this.saqaregistrationDate = saqaregistrationDate;
       this.setaaccreditationDate = setaaccreditationDate;
       this.extensionGranted = extensionGranted;
       this.comments = comments;
    }
   
     /**
      * Gets the id.
      *
      * @return the id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     *
     * @param id the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    
    /**
     * Gets the unit std code.
     *
     * @return the unit std code
     */
    @Column(name="UnitStdCode", precision=22, scale=0)
    public Double getUnitStdCode() {
        return this.unitStdCode;
    }
    
    /**
     * Sets the unit std code.
     *
     * @param unitStdCode the new unit std code
     */
    public void setUnitStdCode(Double unitStdCode) {
        this.unitStdCode = unitStdCode;
    }

    
    /**
     * Gets the unit std desc.
     *
     * @return the unit std desc
     */
    @Column(name="UnitStdDesc")
    public String getUnitStdDesc() {
        return this.unitStdDesc;
    }
    
    /**
     * Sets the unit std desc.
     *
     * @param unitStdDesc the new unit std desc
     */
    public void setUnitStdDesc(String unitStdDesc) {
        this.unitStdDesc = unitStdDesc;
    }

    
    /**
     * Gets the nqflevel.
     *
     * @return the nqflevel
     */
    @Column(name="NQFLevel")
    public String getNqflevel() {
        return this.nqflevel;
    }
    
    /**
     * Sets the nqflevel.
     *
     * @param nqflevel the new nqflevel
     */
    public void setNqflevel(String nqflevel) {
        this.nqflevel = nqflevel;
    }

    
    /**
     * Gets the credit value.
     *
     * @return the credit value
     */
    @Column(name="CreditValue", precision=22, scale=0)
    public Double getCreditValue() {
        return this.creditValue;
    }
    
    /**
     * Sets the credit value.
     *
     * @param creditValue the new credit value
     */
    public void setCreditValue(Double creditValue) {
        this.creditValue = creditValue;
    }

    /**
     * Gets the saqaregistration date.
     *
     * @return the saqaregistration date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SAQARegistrationDate", length=19)
    public Date getSaqaregistrationDate() {
        return this.saqaregistrationDate;
    }
    
    /**
     * Sets the saqaregistration date.
     *
     * @param saqaregistrationDate the new saqaregistration date
     */
    public void setSaqaregistrationDate(Date saqaregistrationDate) {
        this.saqaregistrationDate = saqaregistrationDate;
    }

    /**
     * Gets the setaaccreditation date.
     *
     * @return the setaaccreditation date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SETAAccreditationDate", length=19)
    public Date getSetaaccreditationDate() {
        return this.setaaccreditationDate;
    }
    
    /**
     * Sets the setaaccreditation date.
     *
     * @param setaaccreditationDate the new setaaccreditation date
     */
    public void setSetaaccreditationDate(Date setaaccreditationDate) {
        this.setaaccreditationDate = setaaccreditationDate;
    }

    
    /**
     * Gets the extension granted.
     *
     * @return the extension granted
     */
    @Column(name="ExtensionGranted")
    public String getExtensionGranted() {
        return this.extensionGranted;
    }
    
    /**
     * Sets the extension granted.
     *
     * @param extensionGranted the new extension granted
     */
    public void setExtensionGranted(String extensionGranted) {
        this.extensionGranted = extensionGranted;
    }

    
    /**
     * Gets the comments.
     *
     * @return the comments
     */
    @Column(name="Comments")
    public String getComments() {
        return this.comments;
    }
    
    /**
     * Sets the comments.
     *
     * @param comments the new comments
     */
    public void setComments(String comments) {
        this.comments = comments;
    }




}


