import os
import re
from pathlib import Path
from collections import defaultdict

def extract_pdfs():
    base_dir = r"c:\Antigravity\nsdms-2026-04-01\nsdms\MerSETA"
    reports_dir = Path(base_dir) / "src" / "main" / "webapp" / "reports"
    java_dir = Path(base_dir) / "src" / "main" / "java" / "haj" / "com"
    output_file = Path(base_dir) / "docs" / "generated-pdfs.md"

    # Find all .jrxml and .jasper files
    template_files = set()
    for ext in ["*.jrxml", "*.jasper"]:
        for file_path in reports_dir.rglob(ext):
            template_files.add(file_path.stem) # use stem to ignore extension

    # Scan Java files for references to these templates
    template_usage = defaultdict(list)
    missing_templates = set()
    service_classes = set()

    for root, _, files in os.walk(java_dir):
        for file in files:
            if not file.endswith(".java"): continue
            file_path = Path(root) / file
            
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            for template in template_files:
                if template in content:
                    template_usage[template].append(file.replace(".java", ""))
                    service_classes.add(file.replace(".java", ""))

    # Categorize
    categories = defaultdict(list)
    for template in sorted(template_files):
        prefix = "UNCATEGORIZED"
        if template.startswith("ETQ"): prefix = "ETQA Operations"
        elif template.startswith("LPM"): prefix = "Learner Programmes"
        elif template.startswith("DGD") or template.startswith("DG_") or template.startswith("Discretionary"): prefix = "Discretionary Grants"
        elif template.startswith("WSP") or "WSP" in template: prefix = "Workplace Skills Plan (WSP)"
        elif template.startswith("Assessor") or template.startswith("Moderator"): prefix = "Assessor/Moderator"
        elif template.startswith("Company") or template.startswith("SDF"): prefix = "SDF & Companies"
        elif template.startswith("CSD"): prefix = "CSD Integrations"
        elif "Certificate" in template: prefix = "Certificates"
        elif "Agreement" in template: prefix = "Agreements & Contracts"
        else: prefix = "Other / Administrative"

        categories[prefix].append(template)

    # Generate Markdown
    md_content = ["# MerSETA Generated PDFs Directory\n"]
    md_content.append("This document tracks all PDF templates historically generated by the legacy system (`JasperService`), correlated with the Java services responsible for their invocation.\n")

    for category in sorted(categories.keys()):
        md_content.append(f"## {category}")
        md_content.append("| Template Name | Invoking Java Service / Component |")
        md_content.append("|---|---|")
        for template in sorted(categories[category]):
            services = ", ".join(template_usage.get(template, []))
            if not services: services = "_Not directly invoked (Dynamic/Sub-report/Unused)_"
            md_content.append(f"| `{template}` | {services} |")
        md_content.append("")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(md_content))

    print(f"Successfully generated map of {len(template_files)} PDF templates into {output_file}")

if __name__ == "__main__":
    extract_pdfs()
